name: agora_live_streaming

description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  connectivity_plus: ^4.0.0
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  # dio: ^4.0.6
  # dio_http_cache: ^0.3.0
  cloud_firestore: ^4.7.0
  blurry_modal_progress_hud: ^1.1.0
  flutter_spinkit: ^5.2.0
  firebase_storage: ^11.2.0
  agora_rtc_engine: ^6.1.1
  agora_rtm: ^1.5.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/